### PR TITLE
fixes #38 in which stop failed due to wait in first daemon loop

### LINKED ISSUE #38: Daemon cannot change mode if no ssids available
Once daemon loop starts searching for ssids and no one is found, command to enter in manual mode does not work as it gets stuck searching.

### PR DESCRIPTION
**Pull request by knitzsche**
Start the daemon first loop code more cleanly by removing the flag files *before* the wait-for-external-networks to connect. Thus on entering loop after this, if the daemon has been stopped, the stop file is found and the daemon loop enters manual mode.

### CODE REVIEW

File: daemon/daemon.go [hunk 1]
```diff
@@ -208,12 +210,12 @@ func main() {
 			first = false
 			//clean start require wifi AP down so we can get SSIDs
 			cw.Disable()
-			//TODO only wait if wlan0 is managed
-			//wait time period (TBD) on first run to allow wifi connections
-			time.Sleep(40000 * time.Millisecond)
 			//remove previous state flag, if any on deamon startup
 			utils.RemoveFlagFile(waitFlagPath)
 			utils.RemoveFlagFile(manualFlagPath)
```
Comment (rmescandon) [inline daemon/daemon.go]: sounds to me that before starting the loop these same two lines removing any previous flag file can now be removed. Btw, have you tested nothing is broken with this solution. I thought about this same fix but I was afraid of introducing regressions

Comment (knitzsche) [inline daemon/daemon.go]: right, I'll remove them. and I always (famous last words) test.
