### PR TITLE
Server status

### LINKED ISSUE #29: server.running() does not always return the correct state
Before starting or stopping the mgmt server, the daemon checks the state with server.running(), for example here: https://github.com/CanonicalLtd/UCWifiConnect/blob/master/daemon/daemon.go#L99

The running() method sometimes seems to return an incorrect value, in which case the mgmt server start function [1] is not executed when it should be. The mgmt server startup function code also writes the flag file that controls daemon state. If the flag file is not present, the daemon does not think has entered management mode and loops incorrectly.

For now, I will simply run the methods to start/stop the mgmt server without checking the values first.

[1] https://github.com/CanonicalLtd/UCWifiConnect/blob/master/server/manager.go#L54

### PR DESCRIPTION
**Pull request by rmescandon**
Fixes #29 
Code has been changed to separate server status from current available server. This lets us even add easily other different portals if needed, or add/remove server statuses easily.

Vars to check now are:
- server.Current (can be None, Management, Operational)
- server.State (can be Stopped, Starting, Running, Stopping) 

While starting any server a goroutine checks if the server is already started (by telnet host:port) and moves state from Starting to Running when available.
Server starts asynchronously, so that if you check state just after listenAndServe() call, maybe you still don't get desired server status as it is still in startup process. In case you want main thread to wait for certain server state, there is a server.WaitForState() available method

A bunch of new tests have been added to verify the correct state after valid or invalid transitions.

### CODE REVIEW

File: server/launcher.go [hunk 1]
```diff
@@ -18,47 +18,142 @@
...
+var State = Stopped
+
+var listener net.Listener
+var done chan bool
+
 type tcpKeepAliveListener struct {
 	*net.TCPListener
 }
 
+// WaitForState waits for server reach certaing state
```
Comment (knitzsche) [inline server/launcher.go]: typo "certaing"

File: server/launcher.go [hunk 2]
```diff
@@ -18,47 +18,142 @@
...
 	tc.SetKeepAlivePeriod(3 * time.Minute)
 	return tc, nil
 }
 
-func listenAndServe(addr string, handler http.Handler) (sc io.Closer, err error) {
+func listenAndServe(addr string, handler http.Handler) error {
 
-	var listener net.Listener
+	if State != Stopped {
+		return fmt.Errorf("Server is not in proper stopped state before trying to start it")
```
Comment (knitzsche) [inline server/launcher.go]: can you please change the error text throughout to use this format: "== wifi-connect/server: MSG". It makes it so much easier to find the log messages. (I missed the server when I cleaned up log messages a while back...)

File: utils/utils.go [hunk 3]
```diff
@@ -27,6 +27,10 @@ import (
 	"path/filepath"
 	"sort"
 	"time"
+
+	"strings"
```
Comment (knitzsche) [inline utils/utils.go]: should strings be between sort and time?

File: daemon/daemon.go [hunk 4]
```diff
@@ -164,7 +164,7 @@ func managementServerDown() {
 // operationalServerUp starts the operational server if it is
 // not running
 func operationalServerUp() {
-	if server.Running() != server.OPERATIONAL {
+	if server.Current != server.Operational && server.State == server.Stopped {
```
Comment (knitzsche) [inline daemon/daemon.go]: why is a similar set of conditions not also needed inside managementServerUp()?

File: daemon/daemon.go [hunk 5]
```diff
@@ -176,7 +176,7 @@ func operationalServerUp() {
 
 // operationalServerdown stops the operational server if it is running
 func operationalServerDown() {
-	if server.Running() == server.OPERATIONAL {
+	if server.Current == server.Operational && (server.State == server.Running || server.State == server.Starting) {
```
Comment (knitzsche) [inline daemon/daemon.go]: why is a similar set of conditions not also needed inside managementServerDown()?

**Comment by rmescandon** [comment]
Comments addressed

File: daemon/daemon.go (hunk 4 above)
Comment (knitzsche) [inline daemon/daemon.go]: an answer would be helpful :)

File: daemon/daemon.go (hunk 5 above)
Comment (knitzsche) [inline daemon/daemon.go]: answer would be helpful

File: daemon/daemon.go (hunk 4 above)
Comment (rmescandon) [inline daemon/daemon.go]: They were originally commented out and I didn't realize. Now they are included also

File: daemon/daemon.go (hunk 5 above)
Comment (rmescandon) [inline daemon/daemon.go]: it was originally commented out and I didn't realize. Now it is included also
